// <auto-generated />
using System;
using EasyHome.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EasyHome.Api.Migrations
{
    [DbContext(typeof(EasyHomeDbContext))]
    partial class EasyHomeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EasyHome.Shared.FUTPlayer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<long>("Assists")
                        .HasColumnType("bigint");

                    b.Property<long>("Attackingworkrate")
                        .HasColumnType("bigint");

                    b.Property<string>("AttributeString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Cardsubtypeid")
                        .HasColumnType("bigint");

                    b.Property<long>("Contract")
                        .HasColumnType("bigint");

                    b.Property<long>("Defensiveworkrate")
                        .HasColumnType("bigint");

                    b.Property<long>("DiscardValue")
                        .HasColumnType("bigint");

                    b.Property<long>("FUTID")
                        .HasColumnType("bigint");

                    b.Property<long>("Fitness")
                        .HasColumnType("bigint");

                    b.Property<string>("Formation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("InjuryGames")
                        .HasColumnType("bigint");

                    b.Property<string>("InjuryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LastSalePrice")
                        .HasColumnType("bigint");

                    b.Property<string>("League")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LeagueId")
                        .HasColumnType("bigint");

                    b.Property<long>("LifetimeAssists")
                        .HasColumnType("bigint");

                    b.Property<string>("LifetimeStats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Loans")
                        .HasColumnType("bigint");

                    b.Property<long>("LoyaltyBonus")
                        .HasColumnType("bigint");

                    b.Property<long>("MarketDataMaxPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("MarketDataMinPrice")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Nation")
                        .HasColumnType("bigint");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Owners")
                        .HasColumnType("bigint");

                    b.Property<long>("Pile")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayStyle")
                        .HasColumnType("bigint");

                    b.Property<string>("PreferredPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Preferredfoot")
                        .HasColumnType("bigint");

                    b.Property<long>("Rareflag")
                        .HasColumnType("bigint");

                    b.Property<long>("Rating")
                        .HasColumnType("bigint");

                    b.Property<long>("ResourceGameYear")
                        .HasColumnType("bigint");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint");

                    b.Property<long>("Skillmoves")
                        .HasColumnType("bigint");

                    b.Property<bool>("SkipSBC")
                        .HasColumnType("bit");

                    b.Property<string>("StatsString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Teamid")
                        .HasColumnType("bigint");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("Training")
                        .HasColumnType("bigint");

                    b.Property<long>("Trait1")
                        .HasColumnType("bigint");

                    b.Property<long>("Trait2")
                        .HasColumnType("bigint");

                    b.Property<bool>("Untradeable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("Weakfootabilitytypecode")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("FUTPlayer");
                });

            modelBuilder.Entity("EasyHome.Shared.MSF.MSFCharacter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Allegiance")
                        .HasColumnType("int");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("BasicSkill")
                        .HasColumnType("int");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<string>("Extras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Farmable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Favorite")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Jurisdiction")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organizations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Origin")
                        .HasColumnType("int");

                    b.Property<int>("PassiveSkill")
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<int>("RedStar")
                        .HasColumnType("int");

                    b.Property<int>("Shard")
                        .HasColumnType("int");

                    b.Property<int>("SpecialSkill")
                        .HasColumnType("int");

                    b.Property<int>("Star")
                        .HasColumnType("int");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<int?>("UltimateSkill")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MSFCharacters");
                });

            modelBuilder.Entity("EasyHome.Shared.MSF.MSFCharacterExtra", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MSFCharacterExtra");
                });

            modelBuilder.Entity("EasyHome.Shared.MSF.MSFCharacterOrganization", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MSFCharacterOrganization");
                });

            modelBuilder.Entity("EasyHome.Shared.MSF.MSFTeam", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MSFTeam");
                });
#pragma warning restore 612, 618
        }
    }
}
